### ISSUE TITLE
 RuntimeError(f'<UntrimmedVideoDataset>: got clip of length {vframes.shape[0]} != {self.clip_length}.'

### ISSUE THREAD

**Issue by bruceyo** [HumamAlwassel/TSP#11]
`Traceback (most recent call last):
  File "train.py", line 290, in <module>
    main(args)
  File "train.py", line 260, in main
    train_one_epoch(model=model, criterion=criterion, optimizer=optimizer, lr_scheduler=lr_scheduler,
  File "train.py", line 63, in train_one_epoch
    for sample in metric_logger.log_every(data_loader, print_freq, header, device=device):
  File "/media/bruce/2T/projects/TSP/train/../common/utils.py", line 137, in log_every
    for obj in iterable:
  File "/home/bruce/anaconda2/envs/tsp/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/bruce/anaconda2/envs/tsp/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/bruce/anaconda2/envs/tsp/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/bruce/anaconda2/envs/tsp/lib/python3.8/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/bruce/anaconda2/envs/tsp/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/bruce/anaconda2/envs/tsp/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bruce/anaconda2/envs/tsp/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/bruce/2T/projects/TSP/train/untrimmed_video_dataset.py", line 86, in __getitem__
    raise RuntimeError(f'<UntrimmedVideoDataset>: got clip of length {vframes.shape[0]} != {self.clip_length}.'
RuntimeError: <UntrimmedVideoDataset>: got clip of length 15 != 16.filename=/mnt/nas/bruce14t/THUMOS14/valid/video_validation_0000420.mp4, clip_t_start=526.7160991305855, clip_t_end=527.7827657972522, fps=30.0, t_start=498.2, t_end=546.9`

I am very impressed by your wonderful work. When I try to reproduce the `bash train_tsp_on_thumos14.sh` for the THUMOS14 dataset, I got the above data loading issue. The calculation of the start and end of input clips seems not to work well for all the clips (code Line 74-78 of train/untrimmed_video_dataset.py). Could you provide some help with it? Thank you very much in advance.

**Comment by HumamAlwassel** [comment]
Hello @bruceyo and @NLP-LH,

Thanks for your interest in our work. 
The computation of the start/end times of the input clips is correct. You can see from the error printed that the `clip_t_end` -`clip_t_start` is correctly equal to 16/15 ~= 1.0666667 seconds (this is 16 frames using a 15fps frames rate). Please keep in mind that the code expects a standardized dataset where all videos have a constant frame rate of 30fps. I'm guessing that you may have missed the data preprocessing step from the main [README.md](https://github.com/HumamAlwassel/TSP#data-preprocessing).

Follow the instructions [here](https://github.com/HumamAlwassel/TSP/tree/master/data) to preprocess the input data. Use the `standardize_video_to_constant_30fps_mp4.sh` script to convert the videos into a constant rate of 30fps.

Cheers!
